# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Zhero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zhero
    pod 'Canvas'
  
    pod 'Firebase/Auth'
    pod 'Firebase'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'Kingfisher'
    pod "SearchTextField"
   

end
